/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.seatecnologia.banner.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Banner service. Represents a row in the &quot;Banner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.seatecnologia.banner.model.impl.BannerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.seatecnologia.banner.model.impl.BannerImpl}.
 * </p>
 *
 * @author Oney
 * @see Banner
 * @see br.com.seatecnologia.banner.model.impl.BannerImpl
 * @see br.com.seatecnologia.banner.model.impl.BannerModelImpl
 * @generated
 */
public interface BannerModel extends BaseModel<Banner> {
	/**
	 * Gets the primary key of this banner.
	 *
	 * @return the primary key of this banner
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this banner
	 *
	 * @param primaryKey the primary key of this banner
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Gets the banner ID of this banner.
	 *
	 * @return the banner ID of this banner
	 */
	public long getBannerId();

	/**
	 * Sets the banner ID of this banner.
	 *
	 * @param bannerId the banner ID of this banner
	 */
	public void setBannerId(long bannerId);

	/**
	 * Gets the name of this banner.
	 *
	 * @return the name of this banner
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this banner.
	 *
	 * @param name the name of this banner
	 */
	public void setName(String name);

	/**
	 * Gets the title of this banner.
	 *
	 * @return the title of this banner
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this banner.
	 *
	 * @param title the title of this banner
	 */
	public void setTitle(String title);

	/**
	 * Gets the description of this banner.
	 *
	 * @return the description of this banner
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this banner.
	 *
	 * @param description the description of this banner
	 */
	public void setDescription(String description);

	/**
	 * Gets the link of this banner.
	 *
	 * @return the link of this banner
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this banner.
	 *
	 * @param link the link of this banner
	 */
	public void setLink(String link);

	/**
	 * Gets the image of this banner.
	 *
	 * @return the image of this banner
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this banner.
	 *
	 * @param image the image of this banner
	 */
	public void setImage(String image);

	/**
	 * Gets the position of this banner.
	 *
	 * @return the position of this banner
	 */
	public int getPosition();

	/**
	 * Sets the position of this banner.
	 *
	 * @param position the position of this banner
	 */
	public void setPosition(int position);

	/**
	 * Gets the type of this banner.
	 *
	 * @return the type of this banner
	 */
	public int getType();

	/**
	 * Sets the type of this banner.
	 *
	 * @param type the type of this banner
	 */
	public void setType(int type);

	/**
	 * Gets the status of this banner.
	 *
	 * @return the status of this banner
	 */
	public int getStatus();

	/**
	 * Sets the status of this banner.
	 *
	 * @param status the status of this banner
	 */
	public void setStatus(int status);

	/**
	 * Gets the group ID of this banner.
	 *
	 * @return the group ID of this banner
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this banner.
	 *
	 * @param groupId the group ID of this banner
	 */
	public void setGroupId(long groupId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Banner banner);

	public int hashCode();

	public CacheModel<Banner> toCacheModel();

	public Banner toEscapedModel();

	public String toString();

	public String toXmlString();
}