/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.seatecnologia.banner.model.impl;

import br.com.seatecnologia.banner.model.Banner;
import br.com.seatecnologia.banner.service.BannerLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Banner service. Represents a row in the &quot;Banner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BannerImpl}.
 * </p>
 *
 * @author Oney
 * @see BannerImpl
 * @see br.com.seatecnologia.banner.model.Banner
 * @generated
 */
public abstract class BannerBaseImpl extends BannerModelImpl implements Banner {
	public void persist() throws SystemException {
		BannerLocalServiceUtil.updateBanner(this);
	}
}